openapi: 3.0.0
info:
  title: Simple API
  description: A simple API to demonstrate OpenAPI to C++ stub generation.
  version: 1.0.0

servers:
  - url: http://localhost:8080

paths:
  ## #######   Public API paths    #########
  #
  /public/counter:
    $ref: 'public-api.yaml#/paths/~1counter'

  /public/counters:
    $ref: 'public-api.yaml#/paths/~1counters'

  ## #######   Auth API paths    ###########
  #
  /auth/counter:
    $ref: 'auth-api.yaml#/paths/~1counter'

  /auth/setcounter:
    $ref: 'auth-api.yaml#/paths/~1setcounter'

  ## #######   Test API paths    ###########
  #
  /test/get:
    $ref: 'test-api.yaml#/paths/~1get'

  /test/setcounter:
    $ref: 'test-api.yaml#/paths/~1setcounter'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  responses:
    UnauthorizedError:
      description: Access token is missing or invalid

  schemas:
    GpsPos:
      $ref: 'models-brief.yaml#/components/schemas/GpsPos'
    KeyVal:
      $ref: 'models-brief.yaml#/components/schemas/KeyVal'
    Counter:
      $ref: 'models-brief.yaml#/components/schemas/Counter'
    ItemIdList:
      $ref: 'models-brief.yaml#/components/schemas/ItemIdList'

