openapi: 3.0.0
info:
  title: Simple API
  description: A simple API to demonstrate OpenAPI to C++ stub generation.
  version: 1.0.0

servers:
  - url: http://localhost:8080

paths:
  /public/hello:
    get:
      summary: Returns a greeting message
      description: This endpoint returns a greeting message.
      responses:
        '200':
          description: A greeting message
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Hello, World!"

  /auth/echo:
    post:
      summary: Echoes back the received message
      description: This endpoint takes a message and echoes it back.
      security:
        - bearerAuth: []
      requestBody:
        description: Message to echo back
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                message:
                  type: string
                  example: "Hello"
      responses:
        '200':
          description: Echoed message
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '401':
          $ref: '#/components/responses/UnauthorizedError'

  ## #######   Public API paths    #########
  #
  /public/counter:
    $ref: 'public-api.yaml#/paths/~1counter'

  ## #######   Auth API paths    ###########
  #
  /auth/counter:
    $ref: 'auth-api.yaml#/paths/~1counter'

  /auth/setcounter:
    $ref: 'auth-api.yaml#/paths/~1setcounter'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  responses:
    UnauthorizedError:
      description: Access token is missing or invalid

  schemas:
    GpsPos:
      $ref: 'models-brief.yaml#/components/schemas/GpsPos'
    KeyVal:
      $ref: 'models-brief.yaml#/components/schemas/KeyVal'
    Counter:
      $ref: 'models-brief.yaml#/components/schemas/Counter'
    ItemIdList:
      $ref: 'models-brief.yaml#/components/schemas/ItemIdList'

