/**
* Simple API
* A simple API to demonstrate OpenAPI to C++ stub generation.
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/

/*
* DefaultApiImpl.h
*
* 
*/

#ifndef DEFAULT_API_IMPL_H_
#define DEFAULT_API_IMPL_H_


#include <pistache/endpoint.h>
#include <pistache/http.h>
#include <pistache/router.h>
#include <memory>
#include <optional>

#include <DefaultApi.h>


#include "ItemIdArray.h"
#include "StatList.h"
#include "StatOperation.h"
#include "_auth_echo_post_200_response.h"
#include "_auth_echo_post_request.h"
#include "_public_hello_get_200_response.h"

namespace org::openapitools::server::api
{

using namespace org::openapitools::server::model;

class  DefaultApiImpl : public org::openapitools::server::api::DefaultApi {
public:
    explicit DefaultApiImpl(const std::shared_ptr<Pistache::Rest::Router>& rtr);
    ~DefaultApiImpl() override = default;

    void auth_counter_post(const StatOperation &statOperation, Pistache::Http::ResponseWriter &response);
    void auth_echo_post(const _auth_echo_post_request &authEchoPostRequest, Pistache::Http::ResponseWriter &response);
    void public_counter_post(const ItemIdArray &itemIdArray, Pistache::Http::ResponseWriter &response);
    void public_hello_get(Pistache::Http::ResponseWriter &response);

};

} // namespace org::openapitools::server::api



#endif
