# coding: utf-8

"""
    Simple API

    A simple API to demonstrate OpenAPI to C++ stub generation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class IdKind(str, Enum):
    """
    IdKind
    """

    """
    allowed enum values
    """
    UCAT = 'ucat'
    SELL = 'sell'
    BUYER = 'buyer'
    CUST = 'cust'
    CUSER = 'cuser'
    PROF = 'prof'
    USEC = 'usec'
    UWAR = 'uwar'
    UCON = 'ucon'
    UPRD = 'uprd'
    UTRX = 'utrx'
    UWRK = 'uwrk'
    DLTX = 'dltx'
    DEAL = 'deal'
    REFS = 'refs'
    FEED = 'feed'
    MESG = 'mesg'
    BLOG = 'blog'
    ART = 'art'
    BOOK = 'book'
    CHAPTER = 'chapter'
    STR = 'str'
    FAV = 'fav'
    EMPTY = ''

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of IdKind from a JSON string"""
        return cls(json.loads(json_str))


