# coding: utf-8

"""
    Simple API

    A simple API to demonstrate OpenAPI to C++ stub generation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DefaultApi()

    def tearDown(self) -> None:
        pass

    def test_auth_counter_post(self) -> None:
        """Test case for auth_counter_post

        Create counters having IDs from ItemIdArray.
        """
        pass

    def test_auth_setcounter_post(self) -> None:
        """Test case for auth_setcounter_post

        Change counters for an itemKey
        """
        pass

    def test_public_counter_post(self) -> None:
        """Test case for public_counter_post

        Get counters for an itemId
        """
        pass

    def test_public_counters_get(self) -> None:
        """Test case for public_counters_get

        Get default set of counters.
        """
        pass

    def test_test_get_get(self) -> None:
        """Test case for test_get_get

        A test get API.
        """
        pass

    def test_test_setcounter_post(self) -> None:
        """Test case for test_setcounter_post

        Set a counter with initial values.
        """
        pass


if __name__ == '__main__':
    unittest.main()
