# coding: utf-8

"""
    Simple API

    A simple API to demonstrate OpenAPI to C++ stub generation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.id_kind import IdKind

class TestIdKind(unittest.TestCase):
    """IdKind unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIdKind(self):
        """Test IdKind"""
        # inst = IdKind()

if __name__ == '__main__':
    unittest.main()
