# coding: utf-8

"""
    Simple API

    A simple API to demonstrate OpenAPI to C++ stub generation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.item_id_array import ItemIdArray

class TestItemIdArray(unittest.TestCase):
    """ItemIdArray unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ItemIdArray:
        """Test ItemIdArray
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ItemIdArray`
        """
        model = ItemIdArray()
        if include_optional:
            return ItemIdArray(
                item_key = openapi_client.models.item_key.ItemKey(
                    tag_uuid = '', 
                    elem_uuid = '', 
                    owner_uuid = '', 
                    kind = 'ucat', 
                    seq_no = 56, ),
                item_ids = [
                    openapi_client.models.item_id.ItemId(
                        uuid = '', 
                        kind = 'ucat', 
                        seq_no = 56, )
                    ]
            )
        else:
            return ItemIdArray(
                item_key = openapi_client.models.item_key.ItemKey(
                    tag_uuid = '', 
                    elem_uuid = '', 
                    owner_uuid = '', 
                    kind = 'ucat', 
                    seq_no = 56, ),
                item_ids = [
                    openapi_client.models.item_id.ItemId(
                        uuid = '', 
                        kind = 'ucat', 
                        seq_no = 56, )
                    ],
        )
        """

    def testItemIdArray(self):
        """Test ItemIdArray"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
