# coding: utf-8

"""
    Simple API

    A simple API to demonstrate OpenAPI to C++ stub generation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.stats import Stats

class TestStats(unittest.TestCase):
    """Stats unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Stats:
        """Test Stats
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Stats`
        """
        model = Stats()
        if include_optional:
            return Stats(
                item_id = openapi_client.models.item_id.ItemId(
                    uuid = '', 
                    kind = 'ucat', 
                    seq_no = 56, ),
                likes = 56,
                bookmark = 56,
                shares = 56,
                extras = [
                    openapi_client.models.counter.Counter(
                        name = '', 
                        value = 56, )
                    ]
            )
        else:
            return Stats(
                item_id = openapi_client.models.item_id.ItemId(
                    uuid = '', 
                    kind = 'ucat', 
                    seq_no = 56, ),
        )
        """

    def testStats(self):
        """Test Stats"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
