# coding: utf-8

"""
    Simple API

    A simple API to demonstrate OpenAPI to C++ stub generation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.tag_attr import TagAttr

class TestTagAttr(unittest.TestCase):
    """TagAttr unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TagAttr:
        """Test TagAttr
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TagAttr`
        """
        model = TagAttr()
        if include_optional:
            return TagAttr(
                tag_uuid_key = '',
                tag_rank = 56,
                tag_score = 56,
                up_vote_count = 56,
                down_vote_count = 56,
                shared_count = 56,
                read_count = 56,
                show_count = 56,
                comment_count = 56,
                follow_count = 56,
                book_mark_count = 56,
                blocked_count = 56
            )
        else:
            return TagAttr(
                tag_uuid_key = '',
        )
        """

    def testTagAttr(self):
        """Test TagAttr"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
