/**
* Simple API
* A simple API to demonstrate OpenAPI to C++ stub generation.
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "_auth_echo_post_request.h"
#include "Helpers.h"

#include <sstream>

namespace org::openapitools::server::model
{

_auth_echo_post_request::_auth_echo_post_request()
{
    m_Message = "";
    m_MessageIsSet = false;
    
}

void _auth_echo_post_request::validate() const
{
    std::stringstream msg;
    if (!validate(msg))
    {
        throw org::openapitools::server::helpers::ValidationException(msg.str());
    }
}

bool _auth_echo_post_request::validate(std::stringstream& msg) const
{
    return validate(msg, "");
}

bool _auth_echo_post_request::validate(std::stringstream& msg, const std::string& pathPrefix) const
{
    bool success = true;
    const std::string _pathPrefix = pathPrefix.empty() ? "_auth_echo_post_request" : pathPrefix;

        
    return success;
}

bool _auth_echo_post_request::operator==(const _auth_echo_post_request& rhs) const
{
    return
    
    
    
    ((!messageIsSet() && !rhs.messageIsSet()) || (messageIsSet() && rhs.messageIsSet() && getMessage() == rhs.getMessage()))
    
    ;
}

bool _auth_echo_post_request::operator!=(const _auth_echo_post_request& rhs) const
{
    return !(*this == rhs);
}

void to_json(nlohmann::json& j, const _auth_echo_post_request& o)
{
    j = nlohmann::json::object();
    if(o.messageIsSet())
        j["message"] = o.m_Message;
    
}

void from_json(const nlohmann::json& j, _auth_echo_post_request& o)
{
    if(j.find("message") != j.end())
    {
        j.at("message").get_to(o.m_Message);
        o.m_MessageIsSet = true;
    } 
    
}

std::string _auth_echo_post_request::getMessage() const
{
    return m_Message;
}
void _auth_echo_post_request::setMessage(std::string const& value)
{
    m_Message = value;
    m_MessageIsSet = true;
}
bool _auth_echo_post_request::messageIsSet() const
{
    return m_MessageIsSet;
}
void _auth_echo_post_request::unsetMessage()
{
    m_MessageIsSet = false;
}


} // namespace org::openapitools::server::model

