/**
* Simple API
* A simple API to demonstrate OpenAPI to C++ stub generation.
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "_test_get_get_200_response.h"
#include "Helpers.h"

#include <sstream>

namespace org::openapitools::server::model
{

_test_get_get_200_response::_test_get_get_200_response()
{
    m_Message = "";
    m_MessageIsSet = false;
    
}

void _test_get_get_200_response::validate() const
{
    std::stringstream msg;
    if (!validate(msg))
    {
        throw org::openapitools::server::helpers::ValidationException(msg.str());
    }
}

bool _test_get_get_200_response::validate(std::stringstream& msg) const
{
    return validate(msg, "");
}

bool _test_get_get_200_response::validate(std::stringstream& msg, const std::string& pathPrefix) const
{
    bool success = true;
    const std::string _pathPrefix = pathPrefix.empty() ? "_test_get_get_200_response" : pathPrefix;

        
    return success;
}

bool _test_get_get_200_response::operator==(const _test_get_get_200_response& rhs) const
{
    return
    
    
    
    ((!messageIsSet() && !rhs.messageIsSet()) || (messageIsSet() && rhs.messageIsSet() && getMessage() == rhs.getMessage()))
    
    ;
}

bool _test_get_get_200_response::operator!=(const _test_get_get_200_response& rhs) const
{
    return !(*this == rhs);
}

void to_json(nlohmann::json& j, const _test_get_get_200_response& o)
{
    j = nlohmann::json::object();
    if(o.messageIsSet())
        j["message"] = o.m_Message;
    
}

void from_json(const nlohmann::json& j, _test_get_get_200_response& o)
{
    if(j.find("message") != j.end())
    {
        j.at("message").get_to(o.m_Message);
        o.m_MessageIsSet = true;
    } 
    
}

std::string _test_get_get_200_response::getMessage() const
{
    return m_Message;
}
void _test_get_get_200_response::setMessage(std::string const& value)
{
    m_Message = value;
    m_MessageIsSet = true;
}
bool _test_get_get_200_response::messageIsSet() const
{
    return m_MessageIsSet;
}
void _test_get_get_200_response::unsetMessage()
{
    m_MessageIsSet = false;
}


} // namespace org::openapitools::server::model

