/**
* Simple API
* A simple API to demonstrate OpenAPI to C++ stub generation.
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * Counter.h
 *
 * 
 */

#ifndef Counter_H_
#define Counter_H_


#include <string>
#include <nlohmann/json.hpp>

namespace org::openapitools::server::model
{

/// <summary>
/// 
/// </summary>
class  Counter
{
public:
    Counter();
    virtual ~Counter() = default;


    /// <summary>
    /// Validate the current data in the model. Throws a ValidationException on failure.
    /// </summary>
    void validate() const;

    /// <summary>
    /// Validate the current data in the model. Returns false on error and writes an error
    /// message into the given stringstream.
    /// </summary>
    bool validate(std::stringstream& msg) const;

    /// <summary>
    /// Helper overload for validate. Used when one model stores another model and calls it's validate.
    /// Not meant to be called outside that case.
    /// </summary>
    bool validate(std::stringstream& msg, const std::string& pathPrefix) const;

    bool operator==(const Counter& rhs) const;
    bool operator!=(const Counter& rhs) const;

    /////////////////////////////////////////////
    /// Counter members

    /// <summary>
    /// 
    /// </summary>
    std::string getName() const;
    void setName(std::string const& value);
    /// <summary>
    /// 
    /// </summary>
    int32_t getValue() const;
    void setValue(int32_t const value);

    friend  void to_json(nlohmann::json& j, const Counter& o);
    friend  void from_json(const nlohmann::json& j, Counter& o);
protected:
    std::string m_Name;

    int32_t m_Value;

    
};

} // namespace org::openapitools::server::model

#endif /* Counter_H_ */
