/**
* Simple API
* A simple API to demonstrate OpenAPI to C++ stub generation.
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * GpsPos.h
 *
 * 
 */

#ifndef GpsPos_H_
#define GpsPos_H_


#include "ItemId.h"
#include <nlohmann/json.hpp>

namespace org::openapitools::server::model
{

/// <summary>
/// 
/// </summary>
class  GpsPos
{
public:
    GpsPos();
    virtual ~GpsPos() = default;


    /// <summary>
    /// Validate the current data in the model. Throws a ValidationException on failure.
    /// </summary>
    void validate() const;

    /// <summary>
    /// Validate the current data in the model. Returns false on error and writes an error
    /// message into the given stringstream.
    /// </summary>
    bool validate(std::stringstream& msg) const;

    /// <summary>
    /// Helper overload for validate. Used when one model stores another model and calls it's validate.
    /// Not meant to be called outside that case.
    /// </summary>
    bool validate(std::stringstream& msg, const std::string& pathPrefix) const;

    bool operator==(const GpsPos& rhs) const;
    bool operator!=(const GpsPos& rhs) const;

    /////////////////////////////////////////////
    /// GpsPos members

    /// <summary>
    /// 
    /// </summary>
    org::openapitools::server::model::ItemId getItemId() const;
    void setItemId(org::openapitools::server::model::ItemId const& value);
    /// <summary>
    /// 
    /// </summary>
    double getLng() const;
    void setLng(double const value);
    /// <summary>
    /// 
    /// </summary>
    double getLat() const;
    void setLat(double const value);

    friend  void to_json(nlohmann::json& j, const GpsPos& o);
    friend  void from_json(const nlohmann::json& j, GpsPos& o);
protected:
    org::openapitools::server::model::ItemId m_ItemId;

    double m_Lng;

    double m_Lat;

    
};

} // namespace org::openapitools::server::model

#endif /* GpsPos_H_ */
