/**
* Simple API
* A simple API to demonstrate OpenAPI to C++ stub generation.
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * IdKind.h
 *
 * 
 */

#ifndef IdKind_H_
#define IdKind_H_


#include <nlohmann/json.hpp>

namespace org::openapitools::server::model
{

/// <summary>
/// 
/// </summary>
class  IdKind
{
public:
    IdKind();
    virtual ~IdKind() = default;

    enum class eIdKind {
    // To have a valid default value.
    // Avoiding name clashes with user defined
    // enum values
    INVALID_VALUE_OPENAPI_GENERATED = 0,
    UCAT, 
    SELL, 
    BUYER, 
    CUST, 
    CUSER, 
    PROF, 
    USEC, 
    UWAR, 
    UCON, 
    UPRD, 
    UTRX, 
    UWRK, 
    DLTX, 
    DEAL, 
    REFS, 
    FEED, 
    MESG, 
    BLOG, 
    ART, 
    BOOK, 
    CHAPTER, 
    STR, 
    FAV, 
    EMPTY
    };

    /// <summary>
    /// Validate the current data in the model. Throws a ValidationException on failure.
    /// </summary>
    void validate() const;

    /// <summary>
    /// Validate the current data in the model. Returns false on error and writes an error
    /// message into the given stringstream.
    /// </summary>
    bool validate(std::stringstream& msg) const;

    /// <summary>
    /// Helper overload for validate. Used when one model stores another model and calls it's validate.
    /// Not meant to be called outside that case.
    /// </summary>
    bool validate(std::stringstream& msg, const std::string& pathPrefix) const;

    bool operator==(const IdKind& rhs) const;
    bool operator!=(const IdKind& rhs) const;

    /////////////////////////////////////////////
    /// IdKind members

    IdKind::eIdKind getValue() const;
    void setValue(IdKind::eIdKind value);
    
    friend  void to_json(nlohmann::json& j, const IdKind& o);
    friend  void from_json(const nlohmann::json& j, IdKind& o);
protected:
    IdKind::eIdKind m_value = IdKind::eIdKind::INVALID_VALUE_OPENAPI_GENERATED;
};

} // namespace org::openapitools::server::model

#endif /* IdKind_H_ */
