/**
* Simple API
* A simple API to demonstrate OpenAPI to C++ stub generation.
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "ItemId.h"
#include "Helpers.h"

#include <sstream>

namespace org::openapitools::server::model
{

ItemId::ItemId()
{
    m_Uuid = "";
    m_SeqNo = 0L;
    
}

void ItemId::validate() const
{
    std::stringstream msg;
    if (!validate(msg))
    {
        throw org::openapitools::server::helpers::ValidationException(msg.str());
    }
}

bool ItemId::validate(std::stringstream& msg) const
{
    return validate(msg, "");
}

bool ItemId::validate(std::stringstream& msg, const std::string& pathPrefix) const
{
    bool success = true;
    const std::string _pathPrefix = pathPrefix.empty() ? "ItemId" : pathPrefix;

                
    return success;
}

bool ItemId::operator==(const ItemId& rhs) const
{
    return
    
    
    (getUuid() == rhs.getUuid())
     &&
    
    (getKind() == rhs.getKind())
     &&
    
    (getSeqNo() == rhs.getSeqNo())
    
    
    ;
}

bool ItemId::operator!=(const ItemId& rhs) const
{
    return !(*this == rhs);
}

void to_json(nlohmann::json& j, const ItemId& o)
{
    j = nlohmann::json::object();
    j["uuid"] = o.m_Uuid;
    j["kind"] = o.m_Kind;
    j["seqNo"] = o.m_SeqNo;
    
}

void from_json(const nlohmann::json& j, ItemId& o)
{
    j.at("uuid").get_to(o.m_Uuid);
    j.at("kind").get_to(o.m_Kind);
    j.at("seqNo").get_to(o.m_SeqNo);
    
}

std::string ItemId::getUuid() const
{
    return m_Uuid;
}
void ItemId::setUuid(std::string const& value)
{
    m_Uuid = value;
}
org::openapitools::server::model::IdKind ItemId::getKind() const
{
    return m_Kind;
}
void ItemId::setKind(org::openapitools::server::model::IdKind const& value)
{
    m_Kind = value;
}
int64_t ItemId::getSeqNo() const
{
    return m_SeqNo;
}
void ItemId::setSeqNo(int64_t const value)
{
    m_SeqNo = value;
}


} // namespace org::openapitools::server::model

