/**
* Simple API
* A simple API to demonstrate OpenAPI to C++ stub generation.
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * ItemIdArray.h
 *
 * 
 */

#ifndef ItemIdArray_H_
#define ItemIdArray_H_


#include "ItemKey.h"
#include "ItemId.h"
#include <vector>
#include <nlohmann/json.hpp>

namespace org::openapitools::server::model
{

/// <summary>
/// 
/// </summary>
class  ItemIdArray
{
public:
    ItemIdArray();
    virtual ~ItemIdArray() = default;


    /// <summary>
    /// Validate the current data in the model. Throws a ValidationException on failure.
    /// </summary>
    void validate() const;

    /// <summary>
    /// Validate the current data in the model. Returns false on error and writes an error
    /// message into the given stringstream.
    /// </summary>
    bool validate(std::stringstream& msg) const;

    /// <summary>
    /// Helper overload for validate. Used when one model stores another model and calls it's validate.
    /// Not meant to be called outside that case.
    /// </summary>
    bool validate(std::stringstream& msg, const std::string& pathPrefix) const;

    bool operator==(const ItemIdArray& rhs) const;
    bool operator!=(const ItemIdArray& rhs) const;

    /////////////////////////////////////////////
    /// ItemIdArray members

    /// <summary>
    /// 
    /// </summary>
    org::openapitools::server::model::ItemKey getItemKey() const;
    void setItemKey(org::openapitools::server::model::ItemKey const& value);
    /// <summary>
    /// 
    /// </summary>
    std::vector<org::openapitools::server::model::ItemId> getItemIds() const;
    void setItemIds(std::vector<org::openapitools::server::model::ItemId> const& value);

    friend  void to_json(nlohmann::json& j, const ItemIdArray& o);
    friend  void from_json(const nlohmann::json& j, ItemIdArray& o);
protected:
    org::openapitools::server::model::ItemKey m_ItemKey;

    std::vector<org::openapitools::server::model::ItemId> m_ItemIds;

    
};

} // namespace org::openapitools::server::model

#endif /* ItemIdArray_H_ */
