/**
* Simple API
* A simple API to demonstrate OpenAPI to C++ stub generation.
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * ItemId.h
 *
 * 
 */

#ifndef ItemId_H_
#define ItemId_H_


#include "IdKind.h"
#include <string>
#include <nlohmann/json.hpp>

namespace org::openapitools::server::model
{

/// <summary>
/// 
/// </summary>
class  ItemId
{
public:
    ItemId();
    virtual ~ItemId() = default;


    /// <summary>
    /// Validate the current data in the model. Throws a ValidationException on failure.
    /// </summary>
    void validate() const;

    /// <summary>
    /// Validate the current data in the model. Returns false on error and writes an error
    /// message into the given stringstream.
    /// </summary>
    bool validate(std::stringstream& msg) const;

    /// <summary>
    /// Helper overload for validate. Used when one model stores another model and calls it's validate.
    /// Not meant to be called outside that case.
    /// </summary>
    bool validate(std::stringstream& msg, const std::string& pathPrefix) const;

    bool operator==(const ItemId& rhs) const;
    bool operator!=(const ItemId& rhs) const;

    /////////////////////////////////////////////
    /// ItemId members

    /// <summary>
    /// 
    /// </summary>
    std::string getUuid() const;
    void setUuid(std::string const& value);
    /// <summary>
    /// 
    /// </summary>
    org::openapitools::server::model::IdKind getKind() const;
    void setKind(org::openapitools::server::model::IdKind const& value);
    /// <summary>
    /// 
    /// </summary>
    int64_t getSeqNo() const;
    void setSeqNo(int64_t const value);

    friend  void to_json(nlohmann::json& j, const ItemId& o);
    friend  void from_json(const nlohmann::json& j, ItemId& o);
protected:
    std::string m_Uuid;

    org::openapitools::server::model::IdKind m_Kind;

    int64_t m_SeqNo;

    
};

} // namespace org::openapitools::server::model

#endif /* ItemId_H_ */
