/**
* Simple API
* A simple API to demonstrate OpenAPI to C++ stub generation.
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * ItemKey.h
 *
 * 
 */

#ifndef ItemKey_H_
#define ItemKey_H_


#include "IdKind.h"
#include <string>
#include <nlohmann/json.hpp>

namespace org::openapitools::server::model
{

/// <summary>
/// 
/// </summary>
class  ItemKey
{
public:
    ItemKey();
    virtual ~ItemKey() = default;


    /// <summary>
    /// Validate the current data in the model. Throws a ValidationException on failure.
    /// </summary>
    void validate() const;

    /// <summary>
    /// Validate the current data in the model. Returns false on error and writes an error
    /// message into the given stringstream.
    /// </summary>
    bool validate(std::stringstream& msg) const;

    /// <summary>
    /// Helper overload for validate. Used when one model stores another model and calls it's validate.
    /// Not meant to be called outside that case.
    /// </summary>
    bool validate(std::stringstream& msg, const std::string& pathPrefix) const;

    bool operator==(const ItemKey& rhs) const;
    bool operator!=(const ItemKey& rhs) const;

    /////////////////////////////////////////////
    /// ItemKey members

    /// <summary>
    /// 
    /// </summary>
    std::string getTagUuid() const;
    void setTagUuid(std::string const& value);
    /// <summary>
    /// 
    /// </summary>
    std::string getElemUuid() const;
    void setElemUuid(std::string const& value);
    bool elemUuidIsSet() const;
    void unsetElemUuid();
    /// <summary>
    /// 
    /// </summary>
    std::string getOwnerUuid() const;
    void setOwnerUuid(std::string const& value);
    /// <summary>
    /// 
    /// </summary>
    org::openapitools::server::model::IdKind getKind() const;
    void setKind(org::openapitools::server::model::IdKind const& value);
    /// <summary>
    /// 
    /// </summary>
    int64_t getSeqNo() const;
    void setSeqNo(int64_t const value);

    friend  void to_json(nlohmann::json& j, const ItemKey& o);
    friend  void from_json(const nlohmann::json& j, ItemKey& o);
protected:
    std::string m_TagUuid;

    std::string m_ElemUuid;
    bool m_ElemUuidIsSet;
    std::string m_OwnerUuid;

    org::openapitools::server::model::IdKind m_Kind;

    int64_t m_SeqNo;

    
};

} // namespace org::openapitools::server::model

#endif /* ItemKey_H_ */
