/**
* Simple API
* A simple API to demonstrate OpenAPI to C++ stub generation.
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "KeyVal.h"
#include "Helpers.h"

#include <sstream>

namespace org::openapitools::server::model
{

KeyVal::KeyVal()
{
    m_Key = "";
    m_Value = "";
    
}

void KeyVal::validate() const
{
    std::stringstream msg;
    if (!validate(msg))
    {
        throw org::openapitools::server::helpers::ValidationException(msg.str());
    }
}

bool KeyVal::validate(std::stringstream& msg) const
{
    return validate(msg, "");
}

bool KeyVal::validate(std::stringstream& msg, const std::string& pathPrefix) const
{
    bool success = true;
    const std::string _pathPrefix = pathPrefix.empty() ? "KeyVal" : pathPrefix;

            
    return success;
}

bool KeyVal::operator==(const KeyVal& rhs) const
{
    return
    
    
    (getKey() == rhs.getKey())
     &&
    
    (getValue() == rhs.getValue())
    
    
    ;
}

bool KeyVal::operator!=(const KeyVal& rhs) const
{
    return !(*this == rhs);
}

void to_json(nlohmann::json& j, const KeyVal& o)
{
    j = nlohmann::json::object();
    j["key"] = o.m_Key;
    j["value"] = o.m_Value;
    
}

void from_json(const nlohmann::json& j, KeyVal& o)
{
    j.at("key").get_to(o.m_Key);
    j.at("value").get_to(o.m_Value);
    
}

std::string KeyVal::getKey() const
{
    return m_Key;
}
void KeyVal::setKey(std::string const& value)
{
    m_Key = value;
}
std::string KeyVal::getValue() const
{
    return m_Value;
}
void KeyVal::setValue(std::string const& value)
{
    m_Value = value;
}


} // namespace org::openapitools::server::model

