/**
* Simple API
* A simple API to demonstrate OpenAPI to C++ stub generation.
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * KeyVal.h
 *
 * 
 */

#ifndef KeyVal_H_
#define KeyVal_H_


#include <string>
#include <nlohmann/json.hpp>

namespace org::openapitools::server::model
{

/// <summary>
/// 
/// </summary>
class  KeyVal
{
public:
    KeyVal();
    virtual ~KeyVal() = default;


    /// <summary>
    /// Validate the current data in the model. Throws a ValidationException on failure.
    /// </summary>
    void validate() const;

    /// <summary>
    /// Validate the current data in the model. Returns false on error and writes an error
    /// message into the given stringstream.
    /// </summary>
    bool validate(std::stringstream& msg) const;

    /// <summary>
    /// Helper overload for validate. Used when one model stores another model and calls it's validate.
    /// Not meant to be called outside that case.
    /// </summary>
    bool validate(std::stringstream& msg, const std::string& pathPrefix) const;

    bool operator==(const KeyVal& rhs) const;
    bool operator!=(const KeyVal& rhs) const;

    /////////////////////////////////////////////
    /// KeyVal members

    /// <summary>
    /// 
    /// </summary>
    std::string getKey() const;
    void setKey(std::string const& value);
    /// <summary>
    /// 
    /// </summary>
    std::string getValue() const;
    void setValue(std::string const& value);

    friend  void to_json(nlohmann::json& j, const KeyVal& o);
    friend  void from_json(const nlohmann::json& j, KeyVal& o);
protected:
    std::string m_Key;

    std::string m_Value;

    
};

} // namespace org::openapitools::server::model

#endif /* KeyVal_H_ */
