/**
* Simple API
* A simple API to demonstrate OpenAPI to C++ stub generation.
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * ListCommon.h
 *
 * 
 */

#ifndef ListCommon_H_
#define ListCommon_H_


#include <nlohmann/json.hpp>
#include "ItemId.h"
#include <vector>
#include <nlohmann/json.hpp>

namespace org::openapitools::server::model
{

/// <summary>
/// 
/// </summary>
class  ListCommon
{
public:
    ListCommon();
    virtual ~ListCommon() = default;


    /// <summary>
    /// Validate the current data in the model. Throws a ValidationException on failure.
    /// </summary>
    void validate() const;

    /// <summary>
    /// Validate the current data in the model. Returns false on error and writes an error
    /// message into the given stringstream.
    /// </summary>
    bool validate(std::stringstream& msg) const;

    /// <summary>
    /// Helper overload for validate. Used when one model stores another model and calls it's validate.
    /// Not meant to be called outside that case.
    /// </summary>
    bool validate(std::stringstream& msg, const std::string& pathPrefix) const;

    bool operator==(const ListCommon& rhs) const;
    bool operator!=(const ListCommon& rhs) const;

    /////////////////////////////////////////////
    /// ListCommon members

    /// <summary>
    /// 
    /// </summary>
    nlohmann::json getPageInfo() const;
    void setPageInfo(nlohmann::json const& value);
    /// <summary>
    /// 
    /// </summary>
    std::vector<org::openapitools::server::model::ItemId> getExtras() const;
    void setExtras(std::vector<org::openapitools::server::model::ItemId> const& value);
    bool extrasIsSet() const;
    void unsetExtras();

    friend  void to_json(nlohmann::json& j, const ListCommon& o);
    friend  void from_json(const nlohmann::json& j, ListCommon& o);
protected:
    nlohmann::json m_PageInfo;

    std::vector<org::openapitools::server::model::ItemId> m_Extras;
    bool m_ExtrasIsSet;
    
};

} // namespace org::openapitools::server::model

#endif /* ListCommon_H_ */
