/**
* Simple API
* A simple API to demonstrate OpenAPI to C++ stub generation.
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * PageInfo.h
 *
 * 
 */

#ifndef PageInfo_H_
#define PageInfo_H_


#include <nlohmann/json.hpp>

namespace org::openapitools::server::model
{

/// <summary>
/// 
/// </summary>
class  PageInfo
{
public:
    PageInfo();
    virtual ~PageInfo() = default;


    /// <summary>
    /// Validate the current data in the model. Throws a ValidationException on failure.
    /// </summary>
    void validate() const;

    /// <summary>
    /// Validate the current data in the model. Returns false on error and writes an error
    /// message into the given stringstream.
    /// </summary>
    bool validate(std::stringstream& msg) const;

    /// <summary>
    /// Helper overload for validate. Used when one model stores another model and calls it's validate.
    /// Not meant to be called outside that case.
    /// </summary>
    bool validate(std::stringstream& msg, const std::string& pathPrefix) const;

    bool operator==(const PageInfo& rhs) const;
    bool operator!=(const PageInfo& rhs) const;

    /////////////////////////////////////////////
    /// PageInfo members

    /// <summary>
    /// 
    /// </summary>
    int32_t getTotal() const;
    void setTotal(int32_t const value);
    /// <summary>
    /// 
    /// </summary>
    int32_t getCurrent() const;
    void setCurrent(int32_t const value);
    /// <summary>
    /// 
    /// </summary>
    int64_t getSeqNo() const;
    void setSeqNo(int64_t const value);
    bool seqNoIsSet() const;
    void unsetSeqNo();
    /// <summary>
    /// 
    /// </summary>
    int32_t getItemCount() const;
    void setItemCount(int32_t const value);
    bool itemCountIsSet() const;
    void unsetItemCount();

    friend  void to_json(nlohmann::json& j, const PageInfo& o);
    friend  void from_json(const nlohmann::json& j, PageInfo& o);
protected:
    int32_t m_Total;

    int32_t m_Current;

    int64_t m_SeqNo;
    bool m_SeqNoIsSet;
    int32_t m_ItemCount;
    bool m_ItemCountIsSet;
    
};

} // namespace org::openapitools::server::model

#endif /* PageInfo_H_ */
