/**
* Simple API
* A simple API to demonstrate OpenAPI to C++ stub generation.
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * Signature.h
 *
 * 
 */

#ifndef Signature_H_
#define Signature_H_


#include <string>
#include <nlohmann/json.hpp>

namespace org::openapitools::server::model
{

/// <summary>
/// 
/// </summary>
class  Signature
{
public:
    Signature();
    virtual ~Signature() = default;


    /// <summary>
    /// Validate the current data in the model. Throws a ValidationException on failure.
    /// </summary>
    void validate() const;

    /// <summary>
    /// Validate the current data in the model. Returns false on error and writes an error
    /// message into the given stringstream.
    /// </summary>
    bool validate(std::stringstream& msg) const;

    /// <summary>
    /// Helper overload for validate. Used when one model stores another model and calls it's validate.
    /// Not meant to be called outside that case.
    /// </summary>
    bool validate(std::stringstream& msg, const std::string& pathPrefix) const;

    bool operator==(const Signature& rhs) const;
    bool operator!=(const Signature& rhs) const;

    /////////////////////////////////////////////
    /// Signature members

    /// <summary>
    /// 
    /// </summary>
    std::string getSignedHash() const;
    void setSignedHash(std::string const& value);
    /// <summary>
    /// 
    /// </summary>
    std::string getSValue() const;
    void setSValue(std::string const& value);
    /// <summary>
    /// 
    /// </summary>
    std::string getRValue() const;
    void setRValue(std::string const& value);
    /// <summary>
    /// 
    /// </summary>
    std::string getOp() const;
    void setOp(std::string const& value);

    friend  void to_json(nlohmann::json& j, const Signature& o);
    friend  void from_json(const nlohmann::json& j, Signature& o);
protected:
    std::string m_SignedHash;

    std::string m_SValue;

    std::string m_RValue;

    std::string m_Op;

    
};

} // namespace org::openapitools::server::model

#endif /* Signature_H_ */
