/**
* Simple API
* A simple API to demonstrate OpenAPI to C++ stub generation.
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * StatList.h
 *
 * 
 */

#ifndef StatList_H_
#define StatList_H_


#include "ListCommon.h"
#include <vector>
#include "Stats.h"
#include <nlohmann/json.hpp>

namespace org::openapitools::server::model
{

/// <summary>
/// 
/// </summary>
class  StatList
{
public:
    StatList();
    virtual ~StatList() = default;


    /// <summary>
    /// Validate the current data in the model. Throws a ValidationException on failure.
    /// </summary>
    void validate() const;

    /// <summary>
    /// Validate the current data in the model. Returns false on error and writes an error
    /// message into the given stringstream.
    /// </summary>
    bool validate(std::stringstream& msg) const;

    /// <summary>
    /// Helper overload for validate. Used when one model stores another model and calls it's validate.
    /// Not meant to be called outside that case.
    /// </summary>
    bool validate(std::stringstream& msg, const std::string& pathPrefix) const;

    bool operator==(const StatList& rhs) const;
    bool operator!=(const StatList& rhs) const;

    /////////////////////////////////////////////
    /// StatList members

    /// <summary>
    /// 
    /// </summary>
    org::openapitools::server::model::ListCommon getPage() const;
    void setPage(org::openapitools::server::model::ListCommon const& value);
    /// <summary>
    /// 
    /// </summary>
    std::vector<org::openapitools::server::model::Stats> getList() const;
    void setList(std::vector<org::openapitools::server::model::Stats> const& value);

    friend  void to_json(nlohmann::json& j, const StatList& o);
    friend  void from_json(const nlohmann::json& j, StatList& o);
protected:
    org::openapitools::server::model::ListCommon m_Page;

    std::vector<org::openapitools::server::model::Stats> m_List;

    
};

} // namespace org::openapitools::server::model

#endif /* StatList_H_ */
